### ISSUE TITLE
翻译不统一问题

### ISSUE THREAD

**Issue by MugnusD** [xfl03/sirius-calculator#1]
角色 sense 的分支技能，“センス発動後、追加で[:param11]のプリンシパルゲージを獲得” 的翻译是 “Sense发动后，追加获得[:param11]点P.计量槽”。此处 ”P.计量槽“ 应该统一为 “Principle Gauge”。

比如 id 为 140180 的卡，`sense.descriptionsChinese` 中的两个元素分别是 "获得90点Principle Gauge" 和 "Sense发动后，追加获得30~50点P.计量槽"。

**Comment by xfl03** [comment]
https://github.com/xfl03/sirius-calculator/commit/3b8f4ab1a070aedab004b3ddcaddc76b86103362
